#!/bin/bash

# CCM Save Session Script with Claude-powered Summary Generation
# This script:
# 1. Saves the session as JSONL using session-manager.js
# 2. Reads the last summary (if exists)
# 3. Uses Claude CLI to generate a better summary by merging old + new context
# 4. Updates summaries/latest.md with the new Claude-generated summary

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(dirname "$SCRIPT_DIR")"

# Read hook input from stdin (provided by Claude Code)
HOOK_INPUT=""
if [ ! -t 0 ]; then
    HOOK_INPUT=$(cat)
fi

# Parse transcript path from hook input
TRANSCRIPT_PATH=""
if [ -n "$HOOK_INPUT" ]; then
    TRANSCRIPT_PATH=$(echo "$HOOK_INPUT" | grep -o '"transcript_path":"[^"]*"' | cut -d'"' -f4 || echo "")
fi

# Step 1: Save session using session-manager.js (generates JSONL + basic summary)
# Pass the hook input to session-manager via stdin
if [ -n "$HOOK_INPUT" ]; then
    SAVE_RESULT=$(echo "$HOOK_INPUT" | node "$SCRIPT_DIR/session-manager.js" save)
else
    SAVE_RESULT=$(node "$SCRIPT_DIR/session-manager.js" save "$@")
fi

# Extract session filepath from the result
SESSION_FILE=$(echo "$SAVE_RESULT" | grep -o '"location":"[^"]*"' | cut -d'"' -f4 || echo "")

if [ -z "$SESSION_FILE" ]; then
    echo "$SAVE_RESULT"
    exit 0
fi

# Determine session directory
SESSION_DIR=$(dirname "$SESSION_FILE")
SUMMARY_DIR="$SESSION_DIR/summaries"
LATEST_SUMMARY="$SUMMARY_DIR/latest.md"
DATE_SUMMARY="$SUMMARY_DIR/$(date +%Y-%m-%d).md"

# Step 2: Check if we have a previous summary
PREV_SUMMARY=""
if [ -f "$LATEST_SUMMARY" ]; then
    PREV_SUMMARY=$(cat "$LATEST_SUMMARY")
fi

# Step 3: Generate enhanced summary using Claude CLI
# Only if we have a transcript (not for manual saves)
if [ -n "$TRANSCRIPT_PATH" ] && [ -f "$TRANSCRIPT_PATH" ]; then
    # Check if Claude CLI is available and configured
    if ! command -v claude >/dev/null 2>&1; then
        # Claude CLI not found - inform user
        echo "$SAVE_RESULT"
        echo '{"systemMessage":"⚠️  Claude CLI not found. Install it for AI-powered summaries.\n📖 See README.md for setup instructions: https://github.com/rexzhen/ccm#setup"}' >&2
        exit 0
    fi

    if [ -z "$ANTHROPIC_API_KEY" ]; then
        # API key not set - inform user
        echo "$SAVE_RESULT"
        echo '{"systemMessage":"⚠️  ANTHROPIC_API_KEY not set. Configure it for AI-powered summaries.\n📖 See README.md for setup instructions: https://github.com/rexzhen/ccm#setup"}' >&2
        exit 0
    fi

    # Create a temporary file for the Claude prompt
    TEMP_PROMPT=$(mktemp)

    # Build the prompt for Claude
    cat > "$TEMP_PROMPT" <<'EOF'
You are helping generate a concise, high-quality session summary for Claude Code.

Your task:
1. Read the previous summary (if any) and the new transcript
2. Generate a coherent, deduplicated summary that:
   - Focuses on key decisions made
   - Highlights important outcomes
   - Lists concrete next steps
   - Removes redundancy between old and new content
   - Keeps it concise (under 500 words)

Format the output as markdown with these sections:
- ## Summary (2-3 sentences about what was accomplished)
- ## Key Decisions (bullet points of important choices made)
- ## Outcomes (what was completed or changed)
- ## Next Steps (actionable items for future work)

Be specific and actionable. Avoid vague statements.

EOF

    if [ -n "$PREV_SUMMARY" ]; then
        cat >> "$TEMP_PROMPT" <<EOF

---
## Previous Summary

$PREV_SUMMARY

EOF
    fi

    cat >> "$TEMP_PROMPT" <<EOF

---
## New Session Transcript

EOF

    # Add the transcript content (first 100 lines to keep it reasonable)
    head -100 "$TRANSCRIPT_PATH" >> "$TEMP_PROMPT" 2>/dev/null || echo "No transcript available"

    # Call Claude CLI to generate the summary
    # Use --output-only to get just the response without extra formatting
    NEW_SUMMARY=$(claude --output-only < "$TEMP_PROMPT" 2>/dev/null || echo "")

    # Clean up temp file
    rm -f "$TEMP_PROMPT"

    # Step 4: If Claude generated a summary, use it; otherwise keep the basic one
    if [ -n "$NEW_SUMMARY" ] && [ "$NEW_SUMMARY" != "No transcript available" ]; then
        # Add metadata footer
        FULL_SUMMARY="$NEW_SUMMARY

---
**Session Time:** $(date '+%Y-%m-%d %H:%M:%S')
**Generated by:** CCM Plugin v1.0.4 (Claude-powered)
"

        # Save the enhanced summary
        echo "$FULL_SUMMARY" > "$LATEST_SUMMARY"
        echo "$FULL_SUMMARY" > "$DATE_SUMMARY"

        # Update the session file with the enhanced summary
        if [ -f "$SESSION_FILE" ]; then
            # Read the JSONL, update summary field, write back
            TEMP_SESSION=$(mktemp)
            node -e "
                const fs = require('fs');
                const data = JSON.parse(fs.readFileSync('$SESSION_FILE', 'utf8').trim());
                data.enhancedSummary = \`$FULL_SUMMARY\`;
                fs.writeFileSync('$TEMP_SESSION', JSON.stringify(data) + '\\n');
            " 2>/dev/null && mv "$TEMP_SESSION" "$SESSION_FILE"
        fi

        echo "$SAVE_RESULT"
        echo '{"systemMessage":"✨ Enhanced summary generated using Claude"}' >&2
        exit 0
    fi
fi

# If we get here, just output the original result
echo "$SAVE_RESULT"
