#!/usr/bin/env node

const SessionManager = require('./session-manager.js');
const path = require('path');
const fs = require('fs');

// Get plugin version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
let pluginVersion = '1.0.0';
try {
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  pluginVersion = packageJson.version;
} catch (e) {
  // Use default version if reading fails
}

const manager = new SessionManager();
const fullSummary = manager.getLatestSummary();

// Extract meaningful summary from the session data
let displayMessage = '';
if (fullSummary) {
  // Try to get more context from the actual session JSON file
  const summaryDir = path.join(manager.sessionDir, 'summaries');
  const latestPath = path.join(summaryDir, 'latest.md');

  let sessionDate = '';
  let summary = '';
  let generatedBy = '';

  // Extract the three pieces of information requested

  // 1. Extract Date
  const dateMatch = fullSummary.match(/\*\*Date:\*\* (.+?)$/m);
  if (dateMatch) {
    sessionDate = dateMatch[1].trim();
  }

  // 2. Extract Summary (including bullet points)
  const summaryMatch = fullSummary.match(/## Summary\n([\s\S]+?)(?:\n##|---|\*Generated by)/);
  if (summaryMatch) {
    summary = summaryMatch[1].trim();
    // Clean up
    summary = summary.replace(/Session automatically saved by CCM\./g, '').trim();
    summary = summary.replace(/<[^>]+>/g, '').trim();
    // Preserve line breaks for bullet points but normalize spacing
    summary = summary.split('\n').map(line => line.trim()).filter(line => line).join('\n');
  }

  // 3. Extract "Generated by" version from footer
  const generatedByMatch = fullSummary.match(/\*Generated by (.+?)\*/);
  if (generatedByMatch) {
    generatedBy = generatedByMatch[1].trim();
  }

  // Build the display message with better markdown formatting
  displayMessage = `# CCM Plugin v${pluginVersion}

**Session Memory Active** - Previous session loaded

---

📋 **Last Session:** ${sessionDate || 'Unknown date'}

${summary || 'No summary available'}

---

💡 Quick commands: \`/ccm-save\` | \`/ccm-history\``;

} else {
  displayMessage = `# CCM Plugin v${pluginVersion}

**Session Memory Active** - No previous session found

---

✨ This is a fresh start

---

💡 Quick commands: \`/ccm-save\` | \`/ccm-history\``;
}

// For SessionStart hooks:
// - stdout goes to Claude's context (what Claude sees)
// - JSON systemMessage in stdout goes to user's terminal
// Output as JSON for proper terminal display
const output = {
  systemMessage: displayMessage
};
console.log(JSON.stringify(output));
process.exit(0);
